# Generated by Django 5.2 on 2025-04-11 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_user_social_provider_user_social_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='account_status',
            field=models.CharField(choices=[('pending', 'Pending Verification'), ('active', 'Active'), ('blocked', 'Blocked'), ('suspended', 'Temporarily Suspended')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='additional_documents',
            field=models.FileField(blank=True, help_text='Upload any additional supporting documents', null=True, upload_to='additional_documents/'),
        ),
        migrations.AddField(
            model_name='user',
            name='certification_document',
            field=models.FileField(blank=True, help_text='Upload your professional certification or license', null=True, upload_to='certification_documents/'),
        ),
        migrations.AddField(
            model_name='user',
            name='cv_document',
            field=models.FileField(blank=True, help_text='Upload your professional CV or resume', null=True, upload_to='cv_documents/'),
        ),
        migrations.AddField(
            model_name='user',
            name='date_verified',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_verified_professional',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='license_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='membership_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Monthly membership fee based on user type', max_digits=8),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
        migrations.AddField(
            model_name='user',
            name='quartier',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='town',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='verification_notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
