# Generated by Django 5.2 on 2025-04-11 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_user_campay_reference_user_campay_response_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='payment_receipt',
            field=models.FileField(blank=True, help_text='PDF receipt for membership payment', null=True, upload_to='receipts/'),
        ),
    ]
